In [1]:
import numpy as np
import matplotlib.pyplot as plt
rng = np.random.RandomState(0)

# Trace

**Question** Soient les deux matrices carrées : $\mathbf A = \begin{pmatrix} a&b\\c&d\end{pmatrix}$ et $\mathbf B = \begin{pmatrix} e&f\\g&h\end{pmatrix}$. On rappelle que $vec A$ est la vectorisation de $\mathbf A$, c'est-à-dire la mise bout à bout de toutes les colonnes de la matrice. 

- Quelle est l'expression de la trace de $\mathbf A \mathbf B$? 
- Que vaut $vec(\mathbf A)$ et $vec (\mathbf B^\top)$ et leur produit scalaire.

*Réponse*


**Question** Tirer aléatoirement deux matrices carrées de taille 10 par 10 de valeurs comprimes en -1 et 1 et vérifier cette identité de nombres entre -1 et 1.

In [9]:
A = rng.random((10,10))*2-1
A

array([[-0.197481  ,  0.85858283, -0.80077014,  0.89060307,  0.73897706,
        -0.09167521, -0.34659824, -0.53451174,  0.22892941, -0.93385082],
       [-0.96878787, -0.14240856, -0.86385185, -0.49611802, -0.55767817,
        -0.49361761, -0.73788954, -0.97592755, -0.76903141,  0.23696052],
       [ 0.94851243,  0.98069   , -0.18189181, -0.67409115,  0.27752351,
        -0.01938931,  0.97881955, -0.86939159,  0.56646888, -0.42320301],
       [-0.51716276,  0.32500914, -0.50787363,  0.33171824,  0.03461703,
        -0.15182202,  0.10937562, -0.42589696,  0.41314941, -0.17028626],
       [-0.27890888,  0.65731383,  0.84993382, -0.90798538, -0.53474601,
        -0.30296126,  0.62993296,  0.97098286,  0.93794341,  0.80989669],
       [-0.40688747,  0.98402249, -0.50115992, -0.78818769,  0.90190522,
        -0.53315949,  0.37953653, -0.88328728,  0.4614182 ,  0.76344042],
       [-0.45512621, -0.24188621, -0.25140763,  0.49757652, -0.52438551,
        -0.6562938 , -0.1014167 , -0.39106319

In [8]:
B = rng.random((10,10))*2-1
B

array([[ 0.813111  ,  0.54809467, -0.3337097 , -0.83779722, -0.18551766,
        -0.53553172, -0.73502473, -0.89314564,  0.45118873, -0.97714508],
       [ 0.5411615 , -0.70610671, -0.84095583, -0.82079393,  0.34409561,
        -0.50926558, -0.15892107,  0.11473758,  0.72110235,  0.45408853],
       [-0.45934419, -0.7370344 , -0.88925136, -0.39680273, -0.4757637 ,
        -0.08771887,  0.36656267,  0.39125089, -0.43296231, -0.24014609],
       [-0.63769808,  0.57709102, -0.88630385,  0.39399448,  0.55739079,
         0.55481512, -0.48115487, -0.25237372,  0.17519927, -0.4543562 ],
       [-0.2582944 , -0.60589144, -0.08028823, -0.9107754 ,  0.59959177,
        -0.84608711,  0.0376703 , -0.3863798 ,  0.1550859 ,  0.91886668],
       [ 0.29114049, -0.92927513, -0.13919512,  0.0200337 ,  0.07235499,
         0.36278502, -0.4448078 , -0.74227887, -0.21464865,  0.91281145],
       [-0.62573822,  0.80796791,  0.0876119 , -0.08617716,  0.76408282,
        -0.08279208,  0.44833527, -0.20194936

In [11]:
for elem in A.ravel():
    if elem > 1 or elem < -1:
        print(elem)

In [12]:
for elem in B.ravel():
    if elem > 1 or elem < -1:
        print(elem)

# Base orthonormée

**Question** Constuire une matrice symétrique $\mathbf S$ à partir de $\mathbf M$ en calculant $\mathbf S=\mathbf M+\mathbf M^\top$.

In [13]:
S = A + A.T
S

array([[-0.394962  , -0.11020504,  0.14774229,  0.37344031,  0.46006818,
        -0.49856268, -0.80172445, -0.52973283, -0.62933103, -1.38420368],
       [-0.11020504, -0.28481711,  0.11683815, -0.17110888,  0.09963566,
         0.49040487, -0.97977575, -0.09076035, -1.18344334,  0.42142136],
       [ 0.14774229,  0.11683815, -0.36378362, -1.18196478,  1.12745734,
        -0.52054922,  0.72741192, -0.60139619, -0.12882171,  0.37031931],
       [ 0.37344031, -0.17110888, -1.18196478,  0.66343647, -0.87336834,
        -0.94000971,  0.60695213,  0.30868185,  0.24812216, -0.35681957],
       [ 0.46006818,  0.09963566,  1.12745734, -0.87336834, -1.06949203,
         0.59894396,  0.10554744,  1.85140223,  0.20052207,  0.91405324],
       [-0.49856268,  0.49040487, -0.52054922, -0.94000971,  0.59894396,
        -1.06631898, -0.27675727, -0.38175756,  0.66965381,  0.30674596],
       [-0.80172445, -0.97977575,  0.72741192,  0.60695213,  0.10554744,
        -0.27675727, -0.20283341,  0.00808694

**Question** Calculer la décomposition spectrale de $\mathbf M$ : valeurs propres $\mathbf e$ et vecteurs propres $\mathbf V$

In [15]:
val_p, vec_p  = np.linalg.eig(S)
print("vec_p:")
print(vec_p)
print("val_p:")
print(val_p)

vec_p:
[[-0.13447311  0.19967725  0.35016114 -0.37990288 -0.21993703  0.5412902
   0.34063677  0.27571686 -0.3711482  -0.06273274]
 [-0.20736531 -0.22947868 -0.05177806 -0.28849304 -0.39693647 -0.13100547
   0.00465358 -0.20771483  0.21794048 -0.74366915]
 [-0.07370158 -0.30499911  0.26610897  0.45231571  0.36739608  0.44874403
  -0.19278403 -0.27596883 -0.2357433  -0.34769192]
 [ 0.09396732  0.58714022 -0.03479505  0.33081457 -0.24633533 -0.1755703
  -0.40173236  0.22225786 -0.34633239 -0.33696874]
 [ 0.19328642 -0.40854513 -0.6635243   0.00846668 -0.10815696  0.31623562
  -0.11957677  0.44441922 -0.16910947 -0.05733323]
 [ 0.02817362 -0.23820976  0.34447065  0.35933414  0.06430479 -0.28040851
   0.35263353  0.63777825  0.20285139 -0.19914086]
 [ 0.1435114   0.16853456  0.13259002 -0.43248874  0.48416587  0.15060309
  -0.45101579  0.31106029  0.38913818 -0.19409742]
 [ 0.65815266 -0.16118563  0.36217736  0.0681532  -0.49281832  0.19236632
  -0.20834802 -0.10325171  0.22808268  0.13809

**Question** Calculer le déterminant de $\mathbf S-\lambda \mathbf I$ pour toutes les valeurs propres $\lambda$ dans $\mathbf e$. 

In [26]:
for e in val_p:
    tmp = S - e * np.identity(S.shape[0])
    print(np.linalg.det(tmp))

-2.181126265270723e-09
-9.065005125474304e-12
-1.7303594043278347e-10
-1.5794156090570124e-11
4.717906907882376e-13
-3.3336592429913123e-13
8.830432312130809e-14
-3.9384631301781014e-13
5.833276730623536e-14
-1.3748998632442987e-14


**Question** Calculer $(\mathbf S-\lambda \mathbf I)\mathbf v$ pour tous les couples valeurs propres $\lambda$ et valeur propre associée $\mathbf v$. 

In [29]:
for e, v in zip(val_p, vec_p):
    tmp = (S - e * np.identity(S.shape[0])) * v
    print(np.linalg.det(tmp))
    print(tmp)

2.058882425618745e-15
[[ 6.51453627e-01 -2.20054389e-02  5.17336074e-02 -1.41871049e-01
  -1.01186028e-01 -2.69867092e-01 -2.73096823e-01 -1.46056273e-01
   2.33575076e-01  8.68348924e-02]
 [ 1.48196136e-02 -9.45341034e-01  4.09121802e-02  6.50047569e-02
  -2.19135708e-02  2.65451354e-01 -3.33747642e-01 -2.50241602e-02
   4.39232861e-01 -2.64369173e-02]
 [-1.98673642e-02  2.33299210e-02 -1.68543471e+00  4.49031826e-01
  -2.47969615e-01 -2.81768196e-01  2.47783245e-01 -1.65815070e-01
   4.78119459e-02 -2.32311459e-02]
 [-5.02176782e-02 -3.41665511e-02 -4.13878135e-01  1.43834711e+00
   1.92086037e-01 -5.08818049e-01  2.06750212e-01  8.51087913e-02
  -9.20900927e-02  2.23842701e-02]
 [-6.18667976e-02  1.98949748e-02  3.94791747e-01  3.31795151e-01
   1.21383687e+00  3.24202498e-01  3.59533399e-02  5.10462814e-01
  -7.44234030e-02 -5.73410665e-02]
 [ 6.70432718e-02  9.79226978e-02 -1.82276110e-01  3.57112399e-01
  -1.31729954e-01 -2.98567396e+00 -9.42737021e-02 -1.05256996e-01
  -2.485408

**Question** Vérifier que tous les éléments de $\mathbf V$ sont orthogonaux deux à deux et qu'ils ont une norme 2 égale à 1 : $\langle \mathbf v_i, \mathbf v_j\rangle=0$ et $\langle \mathbf v_i, \mathbf v_i\rangle=1$.

In [35]:
for i in range(len(vec_p)):
    print(np.linalg.norm(vec_p[i]))

0.9999999999999998
1.0
0.9999999999999998
1.0
0.9999999999999998
0.9999999999999996
1.0000000000000002
0.9999999999999997
1.0000000000000002
1.0000000000000002


In [36]:
for i in range(len(vec_p) - 1):
    print(vec_p[i] @ vec_p[i+1].T)

1.3877787807814457e-16
6.800116025829084e-16
2.7755575615628914e-17
6.38378239159465e-16
0.0
3.3306690738754696e-16
-2.220446049250313e-16
-8.326672684688674e-17
1.6653345369377348e-16


In [37]:
vec_p @ vec_p.T

array([[ 1.00000000e+00,  1.31838984e-16,  1.28369537e-16,
         5.55111512e-17,  1.03389519e-15, -4.51028104e-17,
        -1.35308431e-16,  7.28583860e-17, -1.07552856e-16,
        -2.08166817e-17],
       [ 1.31838984e-16,  1.00000000e+00,  7.21644966e-16,
        -5.55111512e-17, -1.38777878e-17, -3.05311332e-16,
        -1.11022302e-16,  1.11022302e-16, -2.22044605e-16,
         1.94289029e-16],
       [ 1.28369537e-16,  7.21644966e-16,  1.00000000e+00,
         0.00000000e+00, -6.59194921e-17,  8.18789481e-16,
        -3.74700271e-16,  3.33066907e-16,  2.22044605e-16,
         2.84494650e-16],
       [ 5.55111512e-17, -5.55111512e-17,  0.00000000e+00,
         1.00000000e+00,  6.83481050e-16, -1.38777878e-16,
        -2.22044605e-16, -3.19189120e-16,  1.38777878e-16,
        -9.71445147e-17],
       [ 1.03389519e-15, -1.38777878e-17, -6.59194921e-17,
         6.83481050e-16,  1.00000000e+00, -3.29597460e-17,
         6.93889390e-18, -1.09287579e-16,  2.11636264e-16,
        -2.

**Question** Calculer la matrice diagonale $\mathbf \Sigma$. Elle a pour diagonale le vecteur $\mathbf e$ et des 0 partout ailleurs. Vérifier que $\mathbf S = \mathbf V\mathbf \Sigma \mathbf V^\top$ et $\mathbf S\mathbf S = \mathbf V\mathbf \Sigma^2 \mathbf V^\top$

In [46]:
sigma = np.diag(val_p)
print(np.allclose(S, vec_p@sigma@vec_p.T))
print(np.allclose(S@S, vec_p@sigma**2@vec_p.T))

True
True


**Question** Vérifier que le déterminant de $\mathbf S$ est bien le produit des valeurs propres. 

In [47]:
np.linalg.det(S)

-106.15368087604753

In [48]:
val_p.prod()

-106.15368087604789

# Méthode des puissances

**Question** Vérifier si la matrice $\mathbf S$ a bien une unique plus grande valeur propre en valeur absolue. Afficher cette valeur propre et le vecteur associé.

In [58]:
val_p

array([ 4.44952806,  2.83777032, -3.52498522, -2.8093907 ,  1.43998825,
        1.06346099,  0.60695017, -1.34639048, -0.69977031, -0.96942526])

In [63]:
pos = np.argmax(np.abs(val_p))
val_p[pos], vec_p[pos]

(4.4495280596736775,
 array([-0.13447311,  0.19967725,  0.35016114, -0.37990288, -0.21993703,
         0.5412902 ,  0.34063677,  0.27571686, -0.3711482 , -0.06273274]))

In [57]:
(val_p[pos] < val_p).sum()

0

**Question** Tirer un vecteur initial aléatoire $\mathbf x$ de taille le nombre de lignes de $\mathbf S$.

In [59]:
x = rng.random(10)
x

array([0.31038083, 0.37303486, 0.52497044, 0.75059502, 0.33350747,
       0.92415877, 0.86231855, 0.0486903 , 0.25364252, 0.44613551])

**Question** Implanter la méthode des puissances itérées pour calculer le premier vecteur propre.

*Rappel* : D'après le cours si on part d'un vecteur quelconque, alors $\frac{\mathbf S^k\mathbf x}{\lVert \mathbf S^k\rVert}$ tend vers ce vecteur.

*Aide* : Pour éviter des problèmes numériques, on normalise à chaque itération.

In [61]:
def iter(x, S, n):
    y = x.copy()
    for _ in range(n):
        y = S@y
        y = y/np.linalg.norm(y)
    return y

In [64]:
print(iter(x, S, 1000))
print("======================")
print(vec_p[pos])

[-0.13447311 -0.20736531 -0.07370158  0.09396732  0.19328642  0.02817362
  0.1435114   0.65815266  0.65371334 -0.07348374]
[-0.13447311  0.19967725  0.35016114 -0.37990288 -0.21993703  0.5412902
  0.34063677  0.27571686 -0.3711482  -0.06273274]


Le quotient de Rayleigh défini par $\frac{\mathbf v^\top \mathbf S^k\mathbf v}{\langle \mathbf v, \mathbf v\rangle}$ dans le cas où $\mathbf v$ est ce vecteur propre est égal à la valeur propre associée. En effet puisque $\mathbf S\mathbf v = \lambda \mathbf v$

$$
\mathbf v^\top \mathbf S\mathbf v = \mathbf v^\top\lambda \mathbf v
$$

$$
\lambda = 
 \frac{\mathbf v^\top \mathbf S\mathbf v}{\langle \mathbf v, \mathbf v\rangle}
$$

**Question** Calculer la valeur propre associée au vecteur propre estimé avec la puissance itérée et comparer avec la vraie valeur.

In [70]:
tmp = iter(x, S, 1000)
l = (tmp.T @ S @ tmp) / (np.linalg.norm(tmp))
l

4.449528059673682

**Question** Calculer le rapport entre la deuxième et la première valeur propre

In [67]:
val_p[1] / val_p[0]

0.6377688325125492

**Question** On va augmenter ce ratio en transformant un peu la matrice $\mathbf S$. Transformez la matrice en prenant sa valeur absolue. Calculez la décomposition spectrale et le ratio précédent. Constatez s'il est plus petit que vous convergez plus vite.

In [72]:
S_abs = np.abs(S)

In [73]:
val2_p, vec2_p  = np.linalg.eig(S_abs)

In [74]:
val2_p[1] / val2_p[0]

0.37823626153533785

In [78]:
0.37823626153533785**10

5.992825381711201e-05

In [79]:
0.37823626153533785**1000

0.0